-- ============================================================
-- PROJECT: Retail Store Database
-- FILE: 03_analysis_queries.sql
-- PURPOSE: A curated set of business questions answered with SQL,
--          ordered from basic to advanced. Great for explaining
--          in an interview -- each query teaches one concept.
-- RUN AFTER: 01_schema.sql and 02_sample_data.sql
-- ============================================================

USE retail_store;

-- ------------------------------------------------------------
-- 1. BASIC: List all products priced above 1000, cheapest first
-- ------------------------------------------------------------
SELECT product_name, price
FROM products
WHERE price > 1000
ORDER BY price ASC;

-- ------------------------------------------------------------
-- 2. BASIC: Find all customers from Bengaluru
-- ------------------------------------------------------------
SELECT first_name, last_name, email
FROM customers
WHERE city = 'Bengaluru';

-- ------------------------------------------------------------
-- 3. AGGREGATE: Total number of orders per status
-- ------------------------------------------------------------
SELECT status, COUNT(*) AS total_orders
FROM orders
GROUP BY status
ORDER BY total_orders DESC;

-- ------------------------------------------------------------
-- 4. AGGREGATE + HAVING: Categories with more than 3 products
-- ------------------------------------------------------------
SELECT c.category_name, COUNT(p.product_id) AS product_count
FROM categories c
JOIN products p ON p.category_id = c.category_id
GROUP BY c.category_name
HAVING COUNT(p.product_id) > 3
ORDER BY product_count DESC;

-- ------------------------------------------------------------
-- 5. JOIN: Revenue generated by each order (excluding cancelled)
-- ------------------------------------------------------------
SELECT
    o.order_id,
    c.first_name,
    c.last_name,
    o.order_date,
    SUM(oi.quantity * oi.unit_price) AS order_total
FROM orders o
JOIN customers c   ON c.customer_id = o.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY o.order_id, c.first_name, c.last_name, o.order_date
ORDER BY order_total DESC;

-- ------------------------------------------------------------
-- 6. LEFT JOIN: Customers who have NEVER placed an order
--    (none in this sample data, but query works if data changes)
-- ------------------------------------------------------------
SELECT c.customer_id, c.first_name, c.last_name
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.customer_id
WHERE o.order_id IS NULL;

-- ------------------------------------------------------------
-- 7. TOP-N: Top 5 best-selling products by quantity sold
-- ------------------------------------------------------------
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_units_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
JOIN orders o   ON o.order_id = oi.order_id
WHERE o.status <> 'Cancelled'
GROUP BY p.product_name
ORDER BY total_units_sold DESC
LIMIT 5;

-- ------------------------------------------------------------
-- 8. SUBQUERY: Customers who spent more than the average
--    customer spend
-- ------------------------------------------------------------
SELECT customer_id, total_spent
FROM (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.unit_price) AS total_spent
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY o.customer_id
) AS customer_totals
WHERE total_spent > (
    SELECT AVG(sub.total_spent)
    FROM (
        SELECT SUM(oi2.quantity * oi2.unit_price) AS total_spent
        FROM orders o2
        JOIN order_items oi2 ON oi2.order_id = o2.order_id
        WHERE o2.status <> 'Cancelled'
        GROUP BY o2.customer_id
    ) AS sub
)
ORDER BY total_spent DESC;

-- ------------------------------------------------------------
-- 9. CTE (Common Table Expression): Monthly revenue trend
-- ------------------------------------------------------------
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT month, revenue
FROM monthly_revenue
ORDER BY month;

-- ------------------------------------------------------------
-- 10. WINDOW FUNCTION: Rank products by revenue within each
--     category (RANK)
-- ------------------------------------------------------------
SELECT
    category_name,
    product_name,
    product_revenue,
    RANK() OVER (PARTITION BY category_name ORDER BY product_revenue DESC) AS rank_in_category
FROM (
    SELECT
        c.category_name,
        p.product_name,
        SUM(oi.quantity * oi.unit_price) AS product_revenue
    FROM order_items oi
    JOIN products p    ON p.product_id = oi.product_id
    JOIN categories c  ON c.category_id = p.category_id
    JOIN orders o       ON o.order_id = oi.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY c.category_name, p.product_name
) AS product_sales
ORDER BY category_name, rank_in_category;

-- ------------------------------------------------------------
-- 11. WINDOW FUNCTION: Running total of daily revenue
-- ------------------------------------------------------------
SELECT
    order_date,
    daily_revenue,
    SUM(daily_revenue) OVER (ORDER BY order_date) AS running_total
FROM (
    SELECT
        o.order_date,
        SUM(oi.quantity * oi.unit_price) AS daily_revenue
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY o.order_date
) AS daily_sales
ORDER BY order_date;

-- ------------------------------------------------------------
-- 12. EMPLOYEE PERFORMANCE: Orders handled and revenue generated
--     per employee
-- ------------------------------------------------------------
SELECT
    e.full_name,
    COUNT(DISTINCT o.order_id) AS orders_handled,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS revenue_generated
FROM employees e
LEFT JOIN orders o       ON o.employee_id = e.employee_id AND o.status <> 'Cancelled'
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY e.full_name
ORDER BY revenue_generated DESC;

-- ------------------------------------------------------------
-- 13. VIEW: Reusable view for customer order summaries
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW customer_order_summary AS
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS lifetime_value
FROM customers c
LEFT JOIN orders o       ON o.customer_id = c.customer_id AND o.status <> 'Cancelled'
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY c.customer_id, c.first_name, c.last_name;

-- Query the view like a normal table:
SELECT * FROM customer_order_summary ORDER BY lifetime_value DESC;

-- ------------------------------------------------------------
-- 14. STORED PROCEDURE: Get full order details for a given
--     order_id (parameterized, reusable)
-- ------------------------------------------------------------
DELIMITER //
CREATE PROCEDURE get_order_details(IN p_order_id INT)
BEGIN
    SELECT
        o.order_id,
        c.first_name,
        c.last_name,
        p.product_name,
        oi.quantity,
        oi.unit_price,
        (oi.quantity * oi.unit_price) AS line_total
    FROM orders o
    JOIN customers c    ON c.customer_id = o.customer_id
    JOIN order_items oi ON oi.order_id = o.order_id
    JOIN products p     ON p.product_id = oi.product_id
    WHERE o.order_id = p_order_id;
END //
DELIMITER ;

-- Call it like this:
-- CALL get_order_details(1);

-- ------------------------------------------------------------
-- 15. CASE STATEMENT: Segment customers by lifetime value
-- ------------------------------------------------------------
SELECT
    customer_id,
    first_name,
    last_name,
    lifetime_value,
    CASE
        WHEN lifetime_value >= 5000 THEN 'Gold'
        WHEN lifetime_value >= 2000 THEN 'Silver'
        WHEN lifetime_value > 0     THEN 'Bronze'
        ELSE 'No Purchases'
    END AS customer_tier
FROM customer_order_summary
ORDER BY lifetime_value DESC;
